export type Region = {
  name: string;
  urlPath: string;
  districts: {
    name: string;
    urlSlug: string;
  }[];
};

export const regions: Region[] = [
  {
    name: "Rīga",
    urlPath: "riga",
    districts: [
      { name: "Āgenskalns", urlSlug: "agenskalns" },
      { name: "Aplokciems", urlSlug: "aplokciems" },
      { name: "Berģi", urlSlug: "bergi" },
      { name: "Bieriņi", urlSlug: "bierini" },
      { name: "Bolderāja", urlSlug: "bolderaya" },
      { name: "Brekši", urlSlug: "breksi" },
      { name: "Bukulti", urlSlug: "bukulti" },
      { name: "Centrs", urlSlug: "centre" },
      { name: "Čiekurkalns", urlSlug: "chiekurkalns" },
      { name: "Dārzciems", urlSlug: "darzciems" },
      { name: "Dārziņi", urlSlug: "darzini" },
      { name: "Daugavgrīva", urlSlug: "daugavgriva" },
      { name: "Dreiliņi", urlSlug: "dreilini" },
      { name: "Dzegužkalns (Dzirciems)", urlSlug: "dzeguzhkalns" },
      { name: "Grīziņkalns", urlSlug: "grizinkalns" },
      { name: "Iļģuciems", urlSlug: "ilguciems" },
      { name: "Imanta", urlSlug: "imanta" },
      { name: "Jāņavārti", urlSlug: "janjavarti" },
      { name: "Jaunciems", urlSlug: "jaunciems" },
      { name: "Jaunmīlgrāvis", urlSlug: "jaunmilgravis" },
      { name: "Jugla", urlSlug: "yugla" },
      { name: "Katlakalns", urlSlug: "katlakalns" },
      { name: "Ķengarags", urlSlug: "kengarags" },
      { name: "Ķīpsala", urlSlug: "kipsala" },
      { name: "Kleisti", urlSlug: "kleisti" },
      { name: "Klīversala", urlSlug: "kliversala" },
      { name: "Krasta r-ns", urlSlug: "krasta-st-area" },
      { name: "Kundziņsala", urlSlug: "kundzinsala" },
      { name: "Latgales priekšpilsēta", urlSlug: "maskavas-priekshpilseta" },
      { name: "Lucavsala", urlSlug: "lucavsala" },
      { name: "Mangaļi", urlSlug: "mangali" },
      { name: "Mangaļsala", urlSlug: "mangalsala" },
      { name: "Mežaparks", urlSlug: "mezhapark" },
      { name: "Mežciems", urlSlug: "mezhciems" },
      { name: "Pļavnieki", urlSlug: "plyavnieki" },
      { name: "Purvciems", urlSlug: "purvciems" },
      { name: "Rumbula", urlSlug: "rumbula" },
      { name: "Sarkandaugava", urlSlug: "sarkandaugava" },
      { name: "Šampēteris-Pleskodāle", urlSlug: "shampeteris-pleskodale" },
      { name: "Šķirotava", urlSlug: "shkirotava" },
      { name: "Teika", urlSlug: "teika" },
      { name: "Torņakalns", urlSlug: "tornjakalns" },
      { name: "Trīsciems", urlSlug: "trisciems" },
      { name: "Vecāķi", urlSlug: "vecaki" },
      { name: "Vecdaugava", urlSlug: "vecdaugava" },
      { name: "Vecmīlgrāvis", urlSlug: "vecmilgravis" },
      { name: "Vecrīga", urlSlug: "vecriga" },
      { name: "VEF", urlSlug: "vef" },
      { name: "Voleri", urlSlug: "voleri" },
      { name: "Zaķusala", urlSlug: "zakusala" },
      { name: "Zasulauks", urlSlug: "zasulauks" },
      { name: "Ziepniekkalns", urlSlug: "ziepniekkalns" },
      { name: "Zolitūde", urlSlug: "zolitude" },
      { name: "Cits", urlSlug: "other" },
      { name: "Visi sludinājumi", urlSlug: "all" },
    ],
  },
  {
    name: "Liepāja",
    urlPath: "liepaja-and-reg",
    districts: [
      { name: "Aizpute", urlSlug: "aizpute" },
      { name: "Durbe", urlSlug: "durbe" },
      { name: "Grobiņa", urlSlug: "grobina" },
      { name: "Liepāja", urlSlug: "liepaja" },
      { name: "Pāvilosta", urlSlug: "pavilosta" },
      { name: "Priekule", urlSlug: "priekule" },
      { name: "Aizputes pag.", urlSlug: "aizputes-pag" },
      { name: "Bārtas pag.", urlSlug: "bartas-pag" },
      { name: "Bunkas pag.", urlSlug: "bunkas-pag" },
      { name: "Dunalkas pag.", urlSlug: "dunalkas-pag" },
      { name: "Gaviezes pag.", urlSlug: "gaviezes-pag" },
      { name: "Grobiņas pag.", urlSlug: "grobinas-pag" },
      { name: "Kalētu pag.", urlSlug: "kaletu-pag" },
      { name: "Medzes pag.", urlSlug: "medzes-pag" },
      { name: "Nīcas pag.", urlSlug: "nicas-pag" },
      { name: "Otaņķu pag.", urlSlug: "otanku-pag" },
      { name: "Priekules pag.", urlSlug: "priekules-pag" },
      { name: "Rucavas pag.", urlSlug: "rucavas-pag" },
      { name: "Sakas pag.", urlSlug: "sakas-pag" },
      { name: "Tadaiķu pag.", urlSlug: "tadaiku-pag" },
      { name: "Vaiņodes pag.", urlSlug: "vainodes-pag" },
      { name: "Virgas pag.", urlSlug: "virgas-pag" },
      { name: "Visi sludinājumi", urlSlug: "all" },
    ],
  },
  {
    name: "Ventspils",
    urlPath: "ventspils-and-reg",
    districts: [
      { name: "Piltene", urlSlug: "piltene" },
      { name: "Ventspils", urlSlug: "ventspils" },
      { name: "Jūrkalnes pag.", urlSlug: "jurkalnes-pag" },
      { name: "Puzes pag.", urlSlug: "puzes-pag" },
      { name: "Tārgales pag.", urlSlug: "targales-pag" },
      { name: "Ugāles pag.", urlSlug: "ugales-pag" },
      { name: "Užavas pag.", urlSlug: "uzavas-pag" },
      { name: "Vārves pag.", urlSlug: "varves-pag" },
      { name: "Visi sludinājumi", urlSlug: "all" },
    ],
  },
];
